### PR TITLE
DYNAMIC SITE NAME

### PR DESCRIPTION
**Pull request by adryxTZ**

### CODE REVIEW

**Review by jackkweyunga — CHANGES_REQUESTED** [review]
ignore files/folders : 
.env 
.idea/ 
db.sqlites3
node_modules 
package-lock.json
venv/

**Comment by adryxTZ** [comment]
> ignore files/folders : .env .idea/ db.sqlites3 node_modules package-lock.json venv/

Done
>  fix(environment variables): REMOVING ENVIRONMENT VARIABLES Removing Environment Variable

**Review by jackkweyunga — COMMENTED** [review]
great. Site name is now dynamic.

**Review by jackkweyunga — APPROVED** [review]

**Comment by jackkweyunga** [comment]
Site name is now dynamic.

**Pull request merged**
